"""Add user_id column to Poll, which refers to the user who created the poll.

Revision ID: 3b9296f51998
Revises: 566994cec6bf
Create Date: 2022-06-30 10:17:20.021944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9296f51998'
down_revision = '566994cec6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poll', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'poll', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poll', type_='foreignkey')
    op.drop_column('poll', 'user_id')
    # ### end Alembic commands ###
