DROP TABLE IF EXISTS poll;
DROP TABLE IF EXISTS poll_question;
DROP TABLE IF EXISTS poll_answer;
DROP TABLE IF EXISTS poll_vote;
DROP TABLE IF EXISTS user;

CREATE TABLE poll (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE poll_question (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  poll_id INTEGER NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (poll_id) REFERENCES poll (id)
);

CREATE TABLE poll_answer (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  poll_id INTEGER NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (poll_id) REFERENCES poll (id)
);

CREATE TABLE poll_vote (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  poll_id INTEGER NOT NULL,
  answer_id INTEGER NOT NULL,
  FOREIGN KEY (poll_id) REFERENCES poll (id),
  FOREIGN KEY (answer_id) REFERENCES poll_answer (id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  password TEXT NOT NULL
)

